### ISSUE TITLE
Don't use `_traces` as a dataset name as the _ prefix is invalid

### ISSUE THREAD

**Issue by RoloEdits** [axiomhq/tracing-axiom#10]
It is an invalid name, and has lead to issues being unable to delete it.

![image](https://github.com/axiomhq/tracing-axiom/assets/12489689/2d5e9fd7-eedd-43af-82cf-936980d23d30)

**Comment by bahlo** [comment]
Hi, this dataset was autocreated, `0.4` adds a mandatory parameter to specify a dataset to send traces .to
