### ISSUE TITLE
Global attributes + field mapping

### ISSUE THREAD

**Issue by ewrogers** [axiomhq/tracing-axiom#14]
We have a single Axiom dataset for our application, and typically use the `environment` field to separate `dev`, `stage`, and `prod`.

There are two problems I am facing currently:

1. Global attributes, I want to essentially have `environment` in every event logged throughout the application. I am just reading this from `ENVIRONMENT` env var. Since my entire application is very async via `tokio`, including `tokio::spawn` for child tasks... it's difficult to get this to "stick". I had thought about a custom layer but it seems events are immutable?

2. Mapping of fields, which seems to always be `attributes.custom.[field]`. In the case of `environment`, I want it to be top-level and not nested within custom attributes. How can I get it to be like this?

I have tried many things but nothing seems to work, and it's a bit confusing considering I am able to get it to work fairly easily with other axiomhq libs (like `pino` in JS).

## Addendum

Turns out, #13 would solve the global attribute issue via `with_tags()`. The mapping of fields is due to Axiom's backend gRPC layer automatically nesting "non-blessed" attributes into `attributes.custom`, which is a bit annoying.

I spun up a simple HTTP proxy to compare [why this works fine in JS land with pino](https://github.com/axiomhq/axiom-js/blob/main/packages/js/src/client.ts#L43). Turns out the JS library sends raw events as `application/json` to `/datasets/:name/ingest` which handles these differently than the `/api/v1/traces` gRPC one.

**Comment by darach** [comment]
Hey @ewrogers Erik,

We have merged #13 so give it a whirl and let us know if it works for your use case.

We're also looking at #12 with an eye to enhancing that as well.

Cheers,

Darach.

**Comment by ewrogers** [comment]
Thanks, I appreciate it! Will definitely be taking a look at this soon.
