### ISSUE TITLE
Traces not showing up

### ISSUE THREAD

**Issue by ziegfried** [axiomhq/tracing-axiom#8]
I tried to setup tracing as described here. I'm not sure where traces are supposed to show up, but I can't find it in any of our datasets. Any pointers appreciated. Not sure where I'm supposed to look for it, since there's also no way to specify the dataset name.

**Comment by ziegfried** [comment]
So I created another organization. When sending traces there (by using an API from that org), it does auto-create a `_traces` dataset. But I don't have such a dataset in the organization I'd like to use. It also won't let me create a dataset with that name. 🤔

**Comment by bahlo** [comment]
Hey @ziegfried, can you try again with `0.4`? That requires you to create a dataset first and specify it in the builder, please re-open if the issue persists 🙌
